<?php

namespace App\Enums;

enum LocationType: string
{
    case MicrosoftTeams = 'microsoft_teams';
    case GoogleMeet = 'google_meet';
    case Phone = 'phone';
    case InviteePhone = 'invitee_phone';
    case InPerson = 'in_person';
    case CustomLink = 'custom_link';

    /**
     * Get the display label for the location type.
     */
    public function label(): string
    {
        return match ($this) {
            self::MicrosoftTeams => 'Microsoft Teams',
            self::GoogleMeet => 'Google Meet',
            self::Phone => 'Phone call (host calls invitee)',
            self::InviteePhone => 'Phone call (invitee calls host)',
            self::InPerson => 'In person',
            self::CustomLink => 'Custom link',
        };
    }

    /**
     * Get a compact label, for places where the full one is too wordy.
     */
    public function shortLabel(): string
    {
        return match ($this) {
            self::MicrosoftTeams => 'Teams',
            self::GoogleMeet => 'Meet',
            self::Phone => 'Phone call',
            self::InviteePhone => 'Invitee calls',
            self::InPerson => 'In person',
            self::CustomLink => 'Custom link',
        };
    }

    /**
     * Determine if the meeting link is generated by a calendar provider.
     */
    public function isGenerated(): bool
    {
        return in_array($this, [self::MicrosoftTeams, self::GoogleMeet], true);
    }

    /**
     * Get the calendar provider that generates this location, if any.
     */
    public function provider(): ?CalendarProvider
    {
        return match ($this) {
            self::MicrosoftTeams => CalendarProvider::Microsoft,
            self::GoogleMeet => CalendarProvider::Google,
            default => null,
        };
    }

    /**
     * Determine if the invitee must supply the location detail when booking.
     */
    public function requiresInviteeInput(): bool
    {
        return $this === self::Phone;
    }

    /**
     * Determine if the host must configure a fixed detail on the event type.
     */
    public function requiresHostDetail(): bool
    {
        return in_array($this, [self::InviteePhone, self::InPerson, self::CustomLink], true);
    }

    /**
     * Get the label for the host supplied detail field.
     */
    public function detailLabel(): ?string
    {
        return match ($this) {
            self::InviteePhone => 'Phone number to call',
            self::InPerson => 'Address',
            self::CustomLink => 'Meeting link',
            default => null,
        };
    }

    /**
     * Get the location types as select options.
     *
     * @return array<array{value: string, label: string, shortLabel: string, isGenerated: bool, requiresHostDetail: bool, detailLabel: string|null}>
     */
    public static function options(): array
    {
        return array_map(fn (self $type) => [
            'value' => $type->value,
            'label' => $type->label(),
            'shortLabel' => $type->shortLabel(),
            'isGenerated' => $type->isGenerated(),
            'requiresHostDetail' => $type->requiresHostDetail(),
            'detailLabel' => $type->detailLabel(),
        ], self::cases());
    }
}
